version: '{build}'
os: Visual Studio 2015 CTP 6
cache:
- src/node_modules
- src/packages
- C:\Users\appveyor\AppData\Roaming\npm-cache
build_script:
- ps: .\build.ps1
test: off
artifacts:
- path: build/*.nupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/cedar/api/v2
  api_key:
    secure: OFKHH+6tRCSObkKF0J5XsgygWyP0piFEoCtwQE99iPzMtoum+a6i6LWhdIEe26Q5
  on:
    branch: master
